on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Verify commit exists in origin/master
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git branch --remote --contains | grep origin/master
      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Build
        run: dotnet build --configuration Release /p:Version=${VERSION}
      - name: Pack
        run: dotnet pack ./ShapeSquareLib/ShapeSquareLib.csproj --configuration Release /p:Version=${VERSION} --no-build --output .
      - name: Push
        run: dotnet nuget push ifelseelif.shape.lib.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_APIKEY}
        env:
          NUGET_APIKEY: ${{ secrets.NUGET_APIKEY }}